# Generated by Django 4.1 on 2022-08-23 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangdo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todolist",
            options={"ordering": ["date"]},
        ),
    ]
