# Generated by Django 4.0.4 on 2022-04-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangdo", "0002_alter_todolist_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
