# Generated by Django 4.2.1 on 2023-05-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_todolist_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="description",
            field=models.TextField(blank=True, default="no description"),
            preserve_default=False,
        ),
    ]
